compressionLevel: mixed

defaultSemverRangePrefix: ''

enableGlobalCache: false

preferReuse: true

yarnPath: .yarn/releases/yarn-remote.cjs

packageExtensions:
  '@module-federation/node@*':
    dependencies:
      tapable: '*'
  next@*:
    peerDependencies:
      webpack: '*'
  rainbow-sprinkles@*:
    dependencies:
      '@vanilla-extract/dynamic': '*'
